<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class TaskRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        $rules =[
            'name'=>'min:1|max:255',
            'description'=>'min:1|max:255',
            'file' =>'file||mimes:jpeg,bmp,png,rar,txt,word,pdf,tgz,zip,php,js,css|max:10000' ,

        ];
        return $rules;
    }
    public function messages()
    {
        return[
            'required' => 'Field :attribute is required' ,
            'min' => 'Field :attribute  must have at least :min characters',
            'max' => 'Field :attribute must have a maximum of :max characters',
            'numeric' => 'Field :attribute field must only contain numbers',
            'unique' => 'Such :attribute exists enter other data',
            'size' => 'The :attribute must be exactly :size.',


        ];

        //  return parent::messages(); // TODO: Change the autogenerated stub
    }
}
